---
title: "DataAnalytics_assignment10"
format: html
editor: visual
---

# Assignment 10 - Practice ANOVA

## Preliminaries

```{r}
#Loading packages
library(tidyverse)
library(skimr)
library(ggplot2)

#Loading in dataset
f <- "https://raw.githubusercontent.com/difiore/ada-datasets/main/AVONETdataset1.csv"
d <- read_csv(f, col_names = TRUE)

#Winnowing the data
d <- select(d, Species1, Family1, Order1, Beak.Length_Culmen, Beak.Width, Beak.Depth, Tarsus.Length, Wing.Length, Tail.Length, Mass, Habitat, Migration, Trophic.Level, Trophic.Niche, Primary.Lifestyle, Min.Latitude, Max.Latitude, Centroid.Latitude, Range.Size)
skim(d)
```

## Challenge 1

### Step 1

```{r}
#Make boxplots of log(Mass) in relation to Trophic.Level and Migration behavior type

#Boxplot of log(Mass) to Trophic.Level
ggplot(data = d %>% 
         drop_na(Trophic.Level), aes(x = Trophic.Level, y = log(Mass))) +
         geom_boxplot()

#Boxplot of log(Mass) to Migration
d1 <- d %>%
  mutate(Migration = as.character(Migration))
ggplot(data = d1 %>% drop_na(Migration), aes(x = Migration, y = log(Mass))) +
  geom_boxplot()
```

### Step 2

```{r}
#Using the lm() function ->  log(Mass) and Trophic.Level
(Mass_TL <- lm(log(Mass) ~ (Trophic.Level), data= d))

#Using the lm() function -> log(Mass) and Migration
(Mass_Migr <- lm(log(Mass) ~ (Migration), data= d1))

#Is log(Mass) associated with either Trophic.Level or Migration category? 
##There is an association between some trophic levels and mass, particularly the scavengers
##There is slight, not statitical significant, inverse relation between mass and migration
```

### Step 3

```{r}
#Conduct a post-hoc Tukey Honest Significant Differences test to also evaluate which Migration categories differ “significantly” from one another
migr_aov <- aov(log(Mass) ~ Migration, data = d1)
posthoc <- TukeyHSD(migr_aov, which = "Migration", ordered = FALSE, conf.level = 0.95)
posthoc  # all age-sex classes differ
```

### Step 4

```{r}
#Preliminaries
set.seed(123)
n <- 1000 #reps
d <- d %>%
  mutate(logM = log(Mass))

#Using the infer package to run the permutation
library(infer)
F_permutation <- d %>%
  specify(logM ~ Trophic.Level) %>%
  hypothesize(null = "independence") %>%
  generate(reps = n, type = "permute") %>%
  calculate(stat = "F")
visualize(F_permutation)

#Pulling out the p-value from the permutation
p <- F_permutation %>%
  get_p_value(obs_stat = F_permutation, direction = "greater")
p #0.35 -> non-significant
```

## Challenge 2

### Step 1

```{r}
##Create a new variable that is 'relative beak length' = residual of log(Beak.Length_Culmen) ~ log(Mass)
n <- lm(log(Beak.Length_Culmen)~ log(Mass), data = d)
d$rel_Beak <- n$residuals
##Relative tarsus length = residual of log(Tarsus.Length) ~log(Mass)
rtl <- lm(log(Tarsus.Length) ~ log(Mass), data =d)
d$rel_Tarsus <- rtl$residuals
```

### Step 2

```{r}
#Make a boxplot of relative tarsus length by primary lifestyle
ggplot(data = d %>% drop_na(Primary.Lifestyle), aes(x = Primary.Lifestyle, y = rel_Tarsus)) +
  geom_boxplot() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1))
#Make a boxplot of relative beak length by trophic niche
ggplot(data = d %>% drop_na(Trophic.Niche), aes(x = Trophic.Niche, y = rel_Beak)) +
  geom_boxplot() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1))
```

### Step 3

```{r}
d <- d %>%
  mutate(logRS = log(d$Range.Size))
d2 <- d %>%
  drop_na(Migration)
histogram(migration$logRS)
#Quite curvy, needs log transformation
histogram(log(migration$Range.Size))

#ANOVA analysis  between geographic range size and migration
GRS_M_aov <- lm(logRS ~ Migration, data = d2)
summary(GRS_M_aov)
#There is a correlation between range size and migration
```

### Step 4

```{r}
##Limit data to the Passeriformes
d1 <- d %>%
  filter(Order1 == "Passeriformes") %>%
  drop_na(Primary.Lifestyle, Trophic.Level) %>%
  mutate(Primary.Lifestyle = as.factor(Primary.Lifestyle), Trophic.Level = as.factor(Trophic.Level))

#Run one-way ANOVA analyses to look at the association between [1] relative beak length and primary lifestyle and 
(aov1 <- aov(data = d1, relbeak ~ Primary.Lifestyle))
##Between 2 relative beak length and trophic niche
(aov2 <- aov(data =d1, relbeak ~ Trophic.Niche))
```

### Step 5

```{r}
#Two-Way ANOVA
m <- aov(relbeak ~ Primary.Lifestyle + Trophic.Level, data = d1)
#or
m <- lm(relbeak ~Primary.Lifestyle + Trophic.Level, data = d1)

summary(m)

#Based on the model output, what would you conclude about how relative beak length is related to these two variables?
##Each grouping variable independently predict relativebeak length
```

### Step 6

```{r}
m <- aov(relbeak ~ Primary.Lifestyle +Trophic.Level + Primary.Lifestyle:Trophic.Level, data = d1)
#or
m <- aov(relbeak ~ Primary.Lifestyle*Trophic.Level, data = d1)
summary(m)

#Based on the model output, what would you now conclude about how relative beak length is related to these two variables?
##Significant interactions between the two variables support the correlation to relative beak size
```

### Step 7

```{r}
#Visualizing interaction effects (with my 'm' model)
library(sjPlot)
library(emmeans)
plot_model(m, 
           type = "emm",
           terms = c("Primary.Lifestyle", "Trophic.Level"))
#Plot marginal means
emmip(m, Trophic.Level ~ Primary.Lifestyle, CIs = TRUE)
#Interpretation -> 
```

### Step 8

```{r}
sd <- d2 %>%
  group_by(Migration) %>%
  summarize(sd = sd(logRS, na.rm = TRUE)) %>%
  pull(sd)
(ratio_sd <- max(sd) / min(sd))
#Ratio -> 1.332764

#Deviated fom normal, so none of this is really statistically valid (whoops)
```
